# Generated by Django 4.2.4 on 2023-11-01 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarcontact',
            name='date',
            field=models.CharField(default=datetime.datetime(2023, 11, 1, 13, 45, 32, 839806), max_length=322, null=True),
        ),
    ]
