# Generated by Django 4.2.4 on 2023-11-03 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback2_alter_webinarcontact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('is_Check', models.BooleanField(default=False)),
                ('textField', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='webinarcontact',
            name='date',
            field=models.CharField(default=datetime.datetime(2023, 11, 3, 11, 9, 37, 217071), max_length=322, null=True),
        ),
    ]
